<pagebreak />
<header class="clearfix">
    <div class="voorwaardentitel"><b>Algemene Voorwaarden <?php echo $this->datobject->user_company; ?></b></div>
</header>
<main>
<div>
<div><b>Toepassing</b></div>

<div>1. Onze algemene voorwaarden zijn van toepassing op alle contracten die worden afgesloten, behoudens uitdrukkelijk anders luidend beding en met uitsluiting van de voorwaarden van de mede-contractant, hierna genoemd klant. De algemene voorwaarden maken integraal deel uit van de contracten en er kan alleen schriftelijk van worden afgeweken.</div>

<div><br/><b>Studies, offertes en overeenkomsten</b></div>

2. Onze offertes zijn slechts bindend wanneer zij door de zaakvoerder werden ondertekend en blijven 1 maand geldig. Indien het BTW-tarief gewijzigd wordt voor de facturatie van het saldo van de prijs, wordt de prijs van de nog te factureren werken overeenkomstig aangepast, zelfs wanneer een prijs inclusief BTW werd overeengekomen. In afwijking van art. 1793 BW kunnen meerwerken met alle middelen van recht worden bewezen.</div>

3. Veiligheidscoördinatie Voorzieningen opgelegd door de veiligheidscoördinator en die niet gekend waren op het ogenblik van het indienen van de oferte, zijn niet in onze offerte begrepen, tenzij anders vermeld. Deze voorzieningen zullen worden doorgerekend aan de klant</div>

4. Energieprestatieregelgeving Voorzieningen opgelegd door de opdrachtgever die niet gekend waren op het ogenblik van het indienen van de offerte, zijn niet in onze offerte begrepen, tenzij anders vermeld. Deze voorzieningen zullen worden doorgerekend aan de klant. De opdracht kan enkel worden uitgevoerd wanneer de aannemer tijdig over de nodige informatie beschikt, vervat in o.a. studies, plannen, documenten, schetsen, tekeningen, stalen en ontwerpen enz.. Deze technische informatie wordt voorafgaand aan de werken overhandigd door de opdrachtgever en of zijn aangestelden (bv. architect of studiebureau). Deze informatie moet tijdig aan de aannemer bezorgd wordt zodat hij over voldoende tijd beschikt om de werken naar behoren voor te bereiden. Bij gebreke hieraan kan de aannemer niet aangesproken worden voor vertragingen of termijnsoverschrijding. De aannemer kan nooit aansprakelijk worden gesteld voor het niet behalen van het E-peil.</div>

<div><br/><b>Uitvoering van de werken</b></div>

5. De uitvoeringstermijn wordt geschorst door onvoorziene omstandigheden buiten de wil van de aannemer om zonder dat een vergoeding verschuldigd is, wanneer de klant hiervan binnen de 14 dagen na het voorval wordt verwittigd en ten laatste op de voorziene uitvoeringsdatum. Wanneer de uitvoeringstermijn wordt opgeschort of onderbroken door de klant of zijn aangestelden of door derden die in opdracht van de klant werken, is de klant een vergoeding verschuldigd voor gederfde winst en kosten. De aannemer bepaalt zelf wanneer hij de werken opnieuw kan aanvatten, zonder dat hiervoor enige vergoeding wegens vertraging verschuldigd is.</div>

6. De goederen worden op risico van de aannemer tot op de werf gebracht. De klant dient ervoor te zorgen dat de goederen bij aankomst onmiddellijk kunnen worden geleverd op de werf en op een veilige manier kunnen worden gestockeerd. Nutteloze verplaatsingskosten en te lange wachttijden (meer dan 15 minuten) zullen worden aangerekend.</div>

7. Na plaatsing van de goederen gaat het risico over op de klant.</div>

8. De niet-geïncorporeerde goederen blijven wel eigendom van de aannemer zolang de factuur m.b.t. deze goederen niet werd betaald.</div>

9. Water, elektriciteit en verwarming zijn te voorzien door de klant.</div>

10. De klant dient te zorgen voor een waterpas en vlakke funderingsplaat tenzij anders in de offerte vermeld.</div>

11. Schuur -en schilderwerken zijn niet in onze offerte opgenomen tenzij dit op de offerte is vermeld.</div>

12. De werf dient door de klant normaal toegankelijk gemaakt te worden en afgewerkt te worden om de normale uitvoering van de werken op een veilige manier mogelijk te maken.</div>

13. De uitvoering van de werken dient te gebeuren volgens de regels van het goed vakmanschap. Deze worden gespecificeerd in de eigenlijke overeenkomst of in de technische voorschriften.</div>

<div><br/><b>Oplevering, onderhoud, waarborg en aansprakelijkheid</b></div>

14. Tenzij anders luidend schriftelijk beding, wordt er overeengekomen dat als er binnen de 8 dagen na de plaatsing geen bemerkingen aangetekend werden overgemaakt aan de aannemer, de aanneming geacht wordt definitief aanvaard te zijn. Dit tijdstip wordt dan ook gelijkgesteld met de enige en definitieve oplevering.</div>

15. De aansprakelijkheid m.b.t. de geleverde en gebruikte producten is beperkt tot de door de fabrikant verstrekte waarborgen.</div>

16. De zichtbare gebreken of de gebreken in de conformiteit welke van bij de plaatsing of de plaatsing bestonden moeten binnen de 8 dagen aangetekend worden gemeld aan de aannemer, zo niet worden zij geacht aanvaard te zijn.</div>

17. Worden niet beschouwd als gebrek in de conformiteit, als een zichtbaar of verborgen gebrek: lichte verschillen in de kleur of textuur of het verkleuren van het hout of het lakwerk, de werking van het hout of lichte verschillen in de afmetingen van goed, voorzover deze vanuit technisch oogpunt niet te voorkomen zijn of algemeen aanvaard zijn of eigen zijn aan de gebruikte materialen.</div>

18. Klachten i.v.m. verborgen gebreken moeten onmiddellijk na de ontdekking worden meegedeeld op straffe van verval. Klachten moeten aangetekend en gedetailleerd worden verstuurd.</div>

19. De 10-jarige aansprakelijkheid voorzien in art. 1792 en 2270 BW is waar wettelijk voorzien van toepassing.</div>

20. Wanneer de overeenkomst verbroken wordt door de klant, zal deze een vergoeding verschuldigd zijn die gelijk is aan de reeds uitgevoerde prestaties en de reeds aangekochte materialen voor de betrokken werf verhoogd met een schadevergoeding van 20% van de overeengekomen prijs. In ieder geval is een minimum vergoeding verschuldigd van 10% van de overeengekomen prijs. De aannemer behoudt zich het recht voor de uitvoering van de aanneming na te streven en een voorschot te vorderen van 10% op de nog niet uitgevoerde werken.</div>

21. Wanneer een factuur niet tijdig betaald wordt, behoudt de aannemer zich het recht voor de uitvoering van het nog uit te voeren werk te onderbreken tot de factuur werd betaald, zonder dat hiervoor enige vergoeding kan verschuldigd zijn door de aannemer. De aannemer bepaalt zelf wanneer hij de werken opnieuw kan aanvatten, zonder dat hiervoor enige vergoeding wegens vertraging verschuldigd is. Wanneer de aannemer door deze schorsing schade lijdt (zowel rechtstreekse als onrechtstreekse), zal de klant deze dienen te vergoeden. Desgevallend kan de aannemer het saldo van de nog uit te voeren werken annuleren.</div>

22. Wanneer de facturen niet tijdig betaald werden, is van rechtswege en zonder enige voorafgaande ingebrekestelling een intrest verschuldigd van 12%. Daarnaast is eveneens van rechtswege en zonder enige bijkomende voorafgaande ingebrekestelling een forfaitaire vergoeding verschuldigd van 10% van het nog verschuldigde bedrag.</div>

23. Bij niet-tijdige betaling van een factuur zullen alle andere nog niet vervallen schuldvorderingen op de klant van rechtswege en zonder voorafgaande ingebrekestelling opeisbaar worden.</div>

<div><br/><b>Betaling</b></div>

<div>24. De betaling dient als volgt te gebeuren:<br/><b><i>
- 50% Voorschot<br/>
- 30% Bij aanvang werken<br/>
- De rest en facturatie is na afsluiting van de werken<br/>
</i></b></div>

25. Tenzij anders vermeld, zijn onze facturen betaalbaar binnen de 14 dagen na factuurdatum op de zetel van de aannemer.</div>

26. Al onze facturen worden geacht aanvaard te zijn wanneer zij niet binnen de 8 dagen na ontvangst bij aangetekend schrijven worden betwist.</div>

<div><br/><b>Bevoegdheid</b></div>

27. Alle geschillen die voortvloeien uit deze overeenkomst zullen worden behandeld voor de rechtbank van Antwerpen.</div>

28. Al onze overeenkomsten worden beheerst door het Belgisch recht.</div>

</div>
</main>

<footer>
</footer>
